const data = [
  {
    id: 1,
    category: "REACT",
    image: "/images/airbnb.jpg",
    title: "Airbnb Clone (In Progress)",
    description: `I am currently working on this Airbnb Clone to showcase my knowledge and understanding of React.js in developing
            modern, responsive and user-friendly applications. I used create react-app and utilised react-router-dom for easy navigations and routing within the app. I am currently using mock data as database on the application, however, I intend to integrate Firebase 9 for the database and authentication.`,
    github: "https://github.com/Danthesage01/airbnb",
    url: "https://zts-airbnb.netlify.app/",
    technology: "JSX, CSS-in-JS, ReactJS & React-Router-DOM",
  },
  {
    id: 2,
    category: "JAVASCRIPT",
    image: "/images/ecommerce-main.jpg",
    title: "Shoe Ecommerce",
    description: `I built the Shoe Ecommerce store to showcase my knowledge and understanding of modern JavaScript (ES6+) which includes AJAX, DOM & Module and internet research skills in creating useful software. Firstly, I created and hosted a Fake REST API server on Heroku that serves as the backend. Then, I fetched the data from the server and massaged them to produce a responsive and interactive ecommerce store. The app features AddToCart, DOM rendering, filters, single-page rendering, and top scroll navigation.`,
    github: "https://github.com/Danthesage01/ecommerce-shoe-vendor",
    url: "https://ecommerce-sv.netlify.app",
    technology: "HTML5, CSS3, JavaScript & ES6+ Modules",
  },
  {
    id: 3,
    category: "REACT",
    image: "/images/shoe-main.jpg",
    title: "Sneakers Ecommerce",
    description: `I developed the Sneakers Ecommerce Website to showcase my knowledge and understanding of JavaScript, ReactJS, and the integration of other third-party technologies such as Netlify Serverless Functions, Auth0 and Stripe to build a modern, responsive and user-friendly ecommerce application for 21st century business outfits. The ecommerce app features a Payment Gateway, User Authentication and other essential ecommerce features.`,
    github: "https://github.com/Danthesage01/sneakers",
    url: "https://re-sneakers.netlify.app",
    technology: "ReactJS, Styled Components(CSS), Auth0 & Stripe, JavaScript",
  },
  {
    id: 4,
    category: "HTML & CSS",
    image: "/images/waka-main.jpg",
    title: "WakaTours",
    description: `I built the wakatours website to showcase my knowledge and understanding of HTML5 &
     CSS3 to develop modern, responsive and user-friendly websites, landing pages and web apps. The wakatours website was designed mainly with CSS Flexbox. Also, I integrated some JavaScript concepts and functions to ensure the website fully dynamically and interactive.`,
    github: "https://github.com/Danthesage01/wakatours-webites",
    url: "https://wakatours.netlify.app",
    technology: "HTML5, CSS3, & JavaScript",
  },
  {
    id: 5,
    category: "REACT",
    image: "/images/quiz-main.jpg",
    title: "Quiz App",
    description: `I developed the Quiz App to showcase my knowledge and understanding of ReactJS in developing
             interactive and responsive single-page applications. I used create react-app in building the App alongside several React Hooks such as the Context API, useEffect, and useState. I consumed a REST API that returns an array of random questions and answers which I massaged to create the quiz app. I got the project idea from one of Scrimba's solo projects.`,
    github: "https://github.com/Danthesage01/quizzical",
    url: "https://r-quizzical.netlify.app/",
    technology: "JSX, CSS3, ReactJS & Context API",
  },
  {
    id: 6,
    category: "HTML & CSS",
    image: "/images/shoe-main.jpg",
    title: "Shoe Vendor",
    description: `I built this Shoe Vendor website to showcase my knowledge and understanding of HTML5 &
     CSS3 to develop modern, responsive and user-friendly websites, landing pages and web apps. The Shoe Vendor website was designed mainly with CSS Float and Animation. Also, I integrated some JavaScript concepts and functions to ensure the website fully dynamically and interactive.`,
    github: "https://github.com/Danthesage01/shoe-vendor",
    url: "https://shoe-vendor.netlify.app",
    technology: "HTML5, CSS3, & JavaScript",
  },
  {
    id: 7,
    category: "JAVASCRIPT",
    image: "/images/color-main.jpg",
    title: "Color Scheme",
    description: `I built the color scheme app to showcase my knowledge and understanding of AJAX in JavaScript. I consumed a color schemed REST API in developing the project and massage the data to build a interactive and responsive user interface. I also used HTML5 & CSS flexbox to make the app fully responsive.`,
    github: "https://github.com/Danthesage01/color-scheme-project",
    url: "https://scheme-color.netlify.app",
    technology: "HTML5, CSS3, & JavaScript",
  },
  {
    id: 8,
    category: "REACT",
    image: "/images/sellCategoryImage.jpg",
    title: "Ib Houses",
    description: `I built the Ib Houses Project to showcase my knowledge and understanding of React.js in developing
            modern, responsive and user-friendly applications. I used create react-app and utilised react-router-dom for easy navigations and routing within the app.`,
    github: "https://github.com/Danthesage01/ibhouses",
    url: "https://ibhouses.netlify.app/",
    technology: "JSX, CSS3, Tailwind, ReactJS, Firebase9",
  },
  {
    id: 9,
    category: "JAVASCRIPT",
    image: "/images/dog-main.jpg",
    title: "Breed of Dogs",
    description: `I built the Breed of Dogs App to showcase my knowledge and understanding of AJAX and JavaScript (ES6+) in consuming REST API in developing useful software. The app features pagination, darkmode, top scroll and single-page rendering.I also used HTML5 & CSS Grid to make the app fully responsive.`,
    github: "https://github.com/Danthesage01/dogAPI",
    url: "https://dogssapi.netlify.app/",
    technology: "HTML5, CSS3, & JavaScript",
  },
  {
    id: 10,
    category: "HTML & CSS",
    image: "/images/about.jpg",
    title: "Portfolio ",
    description: `I built the portfolio website to showcase my knowledge and understanding of HTML5 &
     CSS3 to develop modern, responsive and user-friendly websites, landing pages and web apps. The portfolio was designed mainly with CSS GRID. Also, I integrated some JavaScript concepts and functions to ensure the website fully dynamically and interactive.`,
    github: "https://github.com/Danthesage01/my-portfolio",
    url: "https://daniel-ayeni.netlify.app/",
    technology: "HTML5, CSS3, & JavaScript",
  },
  {
    id: 11,
    category: "REACT",
    image: "/images/guest-main.jpg",
    title: "Guest App",
    description: `I developed the Guestlist App to showcase my knowledge and understanding of ReactJS, Javascript and API in developing
            modern, responsive and user-friendly single-page applications. I used create react-app and utilised react-router-dom for easy navigations and routing within the app. Also, I created and hosted a REST API server on Heroku that serves as the backend where the guests'list is stored and fetched for CRUD operations.`,
    github: "https://github.com/Danthesage01/updated-react-guestapp",
    url: "https://guest-app.netlify.app/",
    technology: "JSX, CSS3, ReactJS & React-Router-DOM",
  },
  {
    id: 12,
    category: "REACT",
    image: "/images/dog-main.jpg",
    title: "Breed of Dogs",
    description: `I built the Breed of Dogs App to showcase my knowledge and understanding of JavaScript (ES6+) and React.js in consuming REST API in developing useful software. The app features pagination, darkmode, and single-page rendering.I also used HTML5 & CSS Grid to make the app fully responsive.`,
    github: "https://github.com/Danthesage01/dogs-app",
    url: "https://dogsreact.netlify.app/",
    technology: "JSX, CSS3, ReactJS & React-Router-DOM",
  },
];

export default data